### ISSUE TITLE
stateofdeno

### ISSUE THREAD

**Issue by sunw31** [denoland/wanted_modules#32]
@lambtron 

this is very important to improve developer experience like stateofjs
https://2021.stateofjs.com/en-US/resources

when I build a app, I need some high quality libraries, ranking list can save my so many time....

| Nodejs ported Module| Deno   Module| CDN convert Module|
| -------------------------|-------------- |-------------------------|
| typeorm   | typeorm@0.25 | not available|
| koa | oak    | oak|

**Comment by lambtron** [comment]
Thanks for adding this. Agree that this is useful. We have noted it. In the meantime I'm closing this issue since this repo is more focused on modules.
