### ISSUE TITLE
xstate 404

### ISSUE THREAD

**Issue by djake** [denoland/wanted_modules#36]
`xstate` is one of the top modules on deno.land/x. 

When I click on it it takes me to the following URL with a 404 error: `https://deno.land/x/xstate@@xstate/svelte@2.0.0`

**Comment by lambtron** [comment]
which link takes you to the 404?

**Comment by djake** [comment]
@lambtron It was just clicking anywhere on the row on the homepage, but appears to be fixed. Thanks for asking, have a great day!

**Comment by ayame113** [comment]
When I access https://deno.land/x/xstate@xstate@4.32.1 and select version `@xstate/svelte@2.0.0`, it seems that 404 is displayed.
I feel that this issue needs to be moved to https://github.com/denoland/dotland.

![image](https://user-images.githubusercontent.com/40050810/168322852-3ca81e91-fc09-4b44-82c3-20c01881eeb9.png)
![image](https://user-images.githubusercontent.com/40050810/168323473-d4a0e96d-93b9-4945-92d4-e93442f330d6.png)
