### ISSUE TITLE
Google Cloud API Client

### ISSUE THREAD

**Issue by ghost** [denoland/wanted_modules#47]
I specifically need features for:
- Pub/Sub streaming
- Cloud build
- Cloud storage
I'm considering porting my deployment system to deno, since I had multiple days of struggle getting nodejs working

**Comment by ry** [comment]
https://googleapis.deno.dev/

**Comment by rojvv** [comment]
@ry Documentation?

**Comment by wallacer** [comment]
I've only tried the SecretManager one, and it doesn't even parse, because the generated comments break things...  eg.
```
* @param name Required. The resource name of the SecretVersion in the format `projects/*/secrets/*/versions/*`. `projects/*/secrets/*/versions/latest` is an alias to the most recently created SecretVersion.
```

`/*` in comments isn't great :P
Bummed I decided to try Deno for my latest project. This is a deal breaker.  Bunch of wasted time...

**Comment by crowlKats** [comment]
@wallacer the project is opensource: https://github.com/lucacasonato/deno_googleapis. Could you open an issue?

**Comment by wallacer** [comment]
@crowlKats done
https://github.com/lucacasonato/deno_googleapis/issues/9

**Comment by crowlKats** [comment]
Will close this issue as the module request is resolved
