### ISSUE TITLE
Request: publish modules from Gitlab

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/wanted_modules#57]
I don't understand why it has to be Github? Why a public repo from Gitlab or anywhere else is not possible? What makes Deno bias Github this much?

**Comment by tristan-f-r** [comment]
The issue attatched is now https://github.com/denoland/apiland/issues/93.

**Comment by crowlKats** [comment]
Closing in favour of https://github.com/denoland/apiland/issues/93
