### ISSUE TITLE
Transferred webhook

### ISSUE THREAD

**Issue by metadream** [denoland/wanted_modules#74]
When the repository is transferred to another account, the webhook will report an error `the module name is registered to a different repository`, but it is correct in the request for transfering. The repo before the transfer is `seatwork/deno-google`, and the repo after the transfer is `metadream/deno-google`.

I don't know where to submit this issue, so here I go. Can you help me?

**Comment by ayame113** [comment]
As commented in https://github.com/denoland/deno_registry2/issues/301#issuecomment-1358181441, it looks like you need to send an email to modules@deno.land .

**Comment by metadream** [comment]
@ayame113 Thanks, I have sent an email to it already.
