### ISSUE TITLE
Bad module name and/or copy right infringement?

### ISSUE THREAD

**Issue by oliver-oloughlin** [denoland/wanted_modules#77]
I published the module "kvdb" (a wrapper/abstraction layer for Deno KV) without realising a product/service with this name already exists: https://kvdb.io

I believe the name therefore might be in violation of their copy right?
If this is the case, I assume my module should be deleted.
I might also add that the versioning is bad due to a misunderstanding on my part on what is good practice in that regard.

If my module is deleted, I would like the chance to re-publish it under a new name and appropriate versioning.

Module link:
https://deno.land/x/kvdb@v1.6.5

**Comment by boywithkeyboard** [comment]
@oliver-oloughlin you should probably contact the Deno team directly via their email: `modules@deno.com`

**Comment by oliver-oloughlin** [comment]
@boywithkeyboard Nice suggestion, thanks.

**Comment by boywithkeyboard** [comment]
@oliver-oloughlin Make sure to close this issue as completed! 😉

**Comment by oliver-oloughlin** [comment]
@boywithkeyboard I will as soon as it is resolved! I haven't heard back from them yet, it is the weekend after all :)

**Comment by boywithkeyboard** [comment]
@oliver-oloughlin I'm just saying that nobody here will be able to help as this repository is rather meant for modules needed by the community which will eventually be ported by the community. There's no involvement here by the Deno staff.

> This repo is for reporting deno modules that currently don't exist, but should.

So you can close this issue right away as it's not the right place to post something like that.

**Comment by oliver-oloughlin** [comment]
@boywithkeyboard I see, I'll close it then. I only posted it here as this was the only place actually referenced by the Deno website itself in regards to issues relating to modules.

**Comment by boywithkeyboard** [comment]
@oliver-oloughlin I'd recommend to ask somebody in Deno's official Discord server next time as most of the people there are really nice and eager to help you. It's always better than opening a issue with your question here.
