### ISSUE TITLE
problem importing deno

### ISSUE THREAD

**Issue by DevelopmentPenguin** [denoland/wanted_modules#78]
i tried to import all modules for deno but i doesnt seem to be working. please help me:

![Capture23](https://github.com/denoland/wanted_modules/assets/113947915/dce8a44e-8b9f-4e82-a574-31d6dd862fb7)

error: File 'c:/Users/NoSweatProgramming/Desktop/dsharp/deno.d.ts' is not a module.

**Comment by bartlomieju** [comment]
`Deno` is a global variable that is always available. It's not module that you need to import.

**Comment by DevelopmentPenguin** [comment]
I know but i have something that needs the import:

![Captur45e](https://github.com/denoland/wanted_modules/assets/113947915/f1587fad-42f2-4fc3-833e-0d2267539914)

If i get rid of the import then i will have an error.

**Comment by bartlomieju** [comment]
What error do you get?

**Comment by DevelopmentPenguin** [comment]
When i got rid of the import?

**Comment by bartlomieju** [comment]
Yes. If your editor is complaining about missing `Deno` global follow the instructions here: https://deno.com/manual@v1.34.0/getting_started/setup_your_environment#using-an-editoride. You don't need to import anything in your code to use `Deno` global.

**Comment by DevelopmentPenguin** [comment]
well, this is the error i got when i deleted the import:   Property 'readTextFile' does not exist on type 'typeof Deno'.

**Comment by bartlomieju** [comment]
Follow the instructions in the above link from the manual. If you still have problem I suggest to join https://discord.gg/deno and message in #help channel.

**Comment by DevelopmentPenguin** [comment]
installing the extension still didnt help

**Comment by DevelopmentPenguin** [comment]
oh nevermind i somehow figured it out. thanks
