### ISSUE TITLE
eden

### ISSUE THREAD

**Issue by jordan-octavia-blue** [denoland/wanted_modules#87]
I just published my own module `eden` but 
- it doesn't show up when searching for it 
- [deno.land/x/eden](https://deno.land/x/eden) 404s 
- when I try to republish the module, it says "Invalid Name/Name has been taken!"

If the name has been taken, why can't I see it when searching for it?

**Comment by crowlKats** [comment]
A module needs a version published before it shows up

**Comment by jordan-octavia-blue** [comment]
@crowlKats Can you clarify "version published"?  There are multiple tagged versions in github and I made a github release and it still doesn't show up in denoland's third party modules.

https://deno.com/add_module says:
> deno.land/x downloads and stores your repository contents every time you create a git tag. We only do this once for every tag. This ensures that the contents we serve for a specific version can never change.

> Our service needs to get informed whenever a new tag is created. For this purpose we use GitHub webhooks.

You can view my tags here: https://github.com/jdoleary/eden-markdown/tags
They've existed for about a week.

**Comment by crowlKats** [comment]
Hm I see. Could you check the webhook deliveries?

**Comment by jordan-octavia-blue** [comment]
Webhook deliveries:
Last delivery: 2023-10-12 08:41:47

Webhook settings:
Payload URL: https://api.deno.land/webhook/gh/eden
Content type: application/json
SSL Verification: Enabled
Events: "Branch or tag creation", "Pushes"
Active: true

**Comment by jordan-octavia-blue** [comment]
Does denoland depend on official github repo releases or just tags?  If it's releases, then maybe I need to push again but I was under the impression that it worked with just tags

**Comment by crowlKats** [comment]
It just works with tags. Please check the response of the delivery as well.

**Comment by jordan-octavia-blue** [comment]
Response is `{"success":false,"info":"created ref is not tag"}`
which is odd because I have 6 tags in my github repo.  Is there a special way that i need to be pushing them?

**Comment by jordan-octavia-blue** [comment]
Okay it looks like it does trigger if I explicitly push a new tag.  I'm still a little fuzzy on how this works and why it didn't work for the previous tags though.

**Comment by jdoleary** [comment]
Now I'm getting a "Module too large" error, which I'll figure out how to resolve on my own.  Nevertheless, maybe the documentation could be a little more specific as to what causes the webhook to trigger?

**Comment by jordan-octavia-blue** [comment]
Maybe I had created the previous tags before setting up the webhook.
