### ISSUE TITLE
"Module not found" for module that definitely exists

### ISSUE THREAD

**Issue by jordan-octavia-blue** [denoland/wanted_modules#88]
`deno run https://deno.land/x/eden@v0.3.7` used to work and now it returns:

`error: Module not found "https://deno.land/x/eden@v0.3.7".`

`deno run https://deno.land/x/eden` also fails.

You can see that the package clearly exists: https://deno.land/x/eden

Thank you for your assistance!

**Comment by bartlomieju** [comment]
Deno doesn't have any special handling for URLs and in your case it's missing the actual file you want to run. Something like `deno run https://deno.land/x/eden@v0.3.7/src/mod.ts` should work correctly 👍

**Comment by jordan-octavia-blue** [comment]
hah, I could've sworn it worked like that previously but I was wrong! Thank you
