### ISSUE TITLE
cannot find `zustand-di` but says name is already taken. 

### ISSUE THREAD

**Issue by charkour** [denoland/wanted_modules#91]
I'm trying to publish my package [`zustand-di`](https://github.com/charkour/zustand-di) to deno.land/x like I was able to with `zundo`, but the UI says this name is already taken. 

Any advice? Thanks!

<img width="648" alt="image" src="https://github.com/denoland/wanted_modules/assets/33156025/5d07bc2f-7ab2-45e4-b79a-11a0b492727c">

<img width="964" alt="image" src="https://github.com/denoland/wanted_modules/assets/33156025/c9f0d690-6828-4eb3-a9d4-827642e4dae8">

**Comment by asdu5asg6da8sjd** [comment]
I'm guessing the `-` is not allowed in package names?

**Comment by asdu5asg6da8sjd** [comment]
> I'm guessing the `-` is not allowed in package names?

yup, `zustanddi` and `zustandi` arent invalid nor taken

**Comment by charkour** [comment]
Thanks for checking, this seems like a bug. I'd like to have `-` in package names like in NPM.

**Comment by charkour** [comment]
Ah, I found out the [package name validation rules](https://deno.land/x/is_valid_package_name@v1.0.0#isvalid) are different for NPM and Deno Land.

**Comment by crowlKats** [comment]
we do not allow `-`, only `_` in module names

**Comment by charkour** [comment]
Thank you for confirming. I'll close this issue.
